import sqlite3
conn = sqlite3.connect(":memory:")
conn.execute("CREATE TABLE pages (id INTEGER PRIMARY KEY AUTOINCREMENT, url TEXT UNIQUE, title TEXT, text TEXT, crawled_at REAL)")
conn.execute("CREATE VIRTUAL TABLE fts_idx USING fts5(url, title, text, content='pages', content_rowid='id')")
conn.execute("CREATE TRIGGER pages_ai AFTER INSERT ON pages BEGIN INSERT INTO fts_idx(rowid, url, title, text) VALUES (new.id, new.url, new.title, new.text); END")
conn.execute("INSERT INTO pages (url, title, text) VALUES ('http://example.com/test', 'Test Page', 'Python async programming tutorial')")
conn.commit()
rows = conn.execute("SELECT url, snippet(fts_idx, 1, '<b>', '</b>', '...', 20), bm25(fts_idx) FROM fts_idx WHERE fts_idx MATCH 'async' ORDER BY bm25(fts_idx)").fetchall()
print("Results:", rows)
conn.close()
print(":memory: FTS5 works!")
